### PR TITLE
Added error logging to file

### LINKED ISSUE #26: [FEATURE] Debug Logging
* **Is your feature request related to a problem? Please describe.**

When errors occur within the app, we currently write to the Console - This is useless as it doesn't output to any file that can be submitted.

---

* **Describe the solution you'd like**

A Logging class that writes all logs to a file and is easily called within the code.

--- 

* **Describe alternatives you've considered**

None.

### PR DESCRIPTION
**Pull request by aseemsahoo**
Resolves #26 

- Now, you can easily check the log file for errors.
- The logging directory is as follows;
` rootdirectory / logs / {year} / {year}-{month} / Error-logs-{date}.txt `

### CODE REVIEW

**Comment by KieranBond** [comment]
Thanks for putting this together @aseemsahoo ! I'll take a look ASAP.

**Comment by KieranBond** [comment]
@aseemsahoo do you know much about Dependency Injection? I think it might be better to inject a singleton FileLogger instance than create a new one each time. What do you think?

**Comment by aseemsahoo** [comment]
> @aseemsahoo do you know much about Dependency Injection?

Unfortunately, I have less idea about it.

> I think it might be better to inject a singleton FileLogger instance than create a new one each time. What do you think?

Yeah, a singleton instance is much better. I'll look into this soon.

**Comment by KieranBond** [comment]
No worries @aseemsahoo!

We can map the `FileLogger` class to a singleton in `MiniSpotify/MiniSpotify/MiniSpotifyConfig.cs` as part of the `Configure` method using this code:
```csharp
context.Mapper.Map<IFileLogger>().BuildValue<FileLogger>();
```

This also requires you to create an interface for the `FileLogger` class to map it against. Once you've done this, then we can get access to the `FileLogger` singleton wherever we like by adding it as a class property like so:
```csharp
public class Example 
{
    //...Some other properties

   [Inject]
   private IFileLogger _fileLogger;

   //...Some other code
}
```

Does that make sense?

**Comment by KieranBond** [comment]
Hey @aseemsahoo, I've committed some changes. Let me know what you think.

**Comment by aseemsahoo** [comment]
> We can map the `FileLogger` class to a singleton in `MiniSpotify/MiniSpotify/MiniSpotifyConfig.cs` as part of the `Configure` method using this code:
> 
> ```cs
> context.Mapper.Map<IFileLogger>().BuildValue<FileLogger>();
> ```
Currently, I'm not proficient in design patterns. So, I'll revisit this later in the future.

**Comment by aseemsahoo** [comment]
> Hey @aseemsahoo, I've committed some changes. Let me know what you think.

Yeah, totally forgot about Path.Combine. Looks more clean as well.

**Review by KieranBond — APPROVED** [review]

**Comment by KieranBond** [comment]
I've gone ahead and merged this - Thanks for your contribution @aseemsahoo!

**Pull request merged**
