### PR TITLE
appearance changes

### PR DESCRIPTION
**Pull request by MBlais13**
!! This is my first time creating a pull request so I'm not sure if I did this correctly.

 * All the vectors used for the UI were stored into /MiniSpotifyPlayerUI.fig  (Figma file).
 * Recolored the UI to match Spotify's desktop application colors.
 * Replaced all UI icons for higher quality ones.
 * Replaced window icons

### CODE REVIEW

**Comment by KieranBond** [comment]
Hiya @MBlais13, thanks for contributing!

I just wanted to say that I'm not ignoring your PR. I'll try to have a look at it this weekend!

A quick glance through; Please remove your changes to the `ReadMe.md`. The `ReadMe` is specifically for introducing people to the project and providing documentation, not for listing the changes - I'll add them to the release that will spawn from this PR :)

**Comment by KieranBond** [comment]
What's the purpose of using a figma file instead of the vectors as they were @MBlais13? It's not a file type I've heard of before.

**Comment by MBlais13** [comment]
I had left the Figma file in there so if someone wanted to see/change all the vector icons they would all be in 1 file. Figma is an adobe xd alternative and I use it as a prototyping tool.

image

**Comment by KieranBond** [comment]
Thanks for the contribution @MBlais13! I'll create a release with your changes.

**Comment by KieranBond** [comment]
Release with your UI update is here: https://github.com/KieranBond/MiniSpotify/releases/tag/v3.0

**Pull request merged**
